name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on:
      group: npm-deploy
    environment:
      name: upload
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build list
        run: yarn build

      # - name: Pin to IPFS
      #   id: upload
      #   uses: anantaramdas/ipfs-pinata-deploy-action@a551f37c17ec3961df7c3ad52e1cd266dfd3d7e7
      #   with:
      #     pin-name: Uniswap Default Token List
      #     path: "build/uniswap-default.tokenlist.json"
      #     pinata-api-key: ${{ secrets.PINATA_API_KEY }}
      #     pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      # - name: Update DNS with new IPFS hash
      #   env:
      #     CLOUDFLARE_TOKEN: ${{ env.CLOUDFLARE_TOKEN }}
      #     CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      #     CLOUDFLARE_GATEWAY_ID: ${{ secrets.CLOUDFLARE_GATEWAY_ID }}
      #   uses: Uniswap/cloudflare-update-web3-gateway@b3205288b1c6d0acb63fa3bd8fb686c72a9e3f3e
      #   with:
      #     cid: ${{ steps.upload.outputs.hash }}
